package tv.purple.monolith.component.api.di.scope

const val BTTV = "bttv"
const val CHATTERINO = "chatterino"
const val NOP = "nop"
const val FFZAP = "ffzap"
const val FFZ = "ffz"
const val STV = "stv"
const val STV_OLD_API = "stv_old"
const val PRN = "pronouns"
const val GQL = "GQL"
const val HOMIES = "homies"
const val FLXRS = "flxrs"
const val CHATSEN = "chatsen"
const val CHATSEN2 = "chatsen2"
