name: Android CI Build Debug APK (Manual)

on:
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Checks out your repository code

      - name: Set up JDK 17 # Changed step name for clarity
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Changed from '17' to '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./app/

      - name: Build Debug APK
        run: ./gradlew assembleDebug --warning-mode=none --scan
        working-directory: ./app/
        

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
